<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">

  <name>ros2_coding_round</name>

  <version>0.0.0</version>

  <description>
    ROS 2 coding round solutions.
  </description>

  <maintainer email="derrick@example.com">
    derrick
  </maintainer>

  <license>Apache-2.0</license>

  <!-- ROS 2 build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS 2 -->
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>

  <!-- Messages -->
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>

  <!-- TF2 -->
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>

  <!-- Nav2 -->
  <depend>nav2_core</depend>
  <depend>nav2_costmap_2d</depend>

  <!-- Pluginlib -->
  <depend>pluginlib</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
